#!/usr/bin/env node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const source = path.join(repoRoot, 'packages', 'karen', 'bin', 'karen.js');
const packageJson = path.join(repoRoot, 'packages', 'karen', 'package.json');
const isWindows = process.platform === 'win32';
const commandName = isWindows ? 'karen.cmd' : 'karen';

const usage = `Karen installer

Usage:
  bun run install:karen                  Install the karen command
  bun run install:karen -- status        Show install status
  bun run install:karen -- doctor        Check PATH, runtime, and OpenCode
  bun run install:karen -- uninstall     Remove the installed command

Options:
  --dir <path>      Install directory. Defaults to $KAREN_INSTALL_DIR or ~/.local/bin
  --force           Replace an existing karen command not owned by this repo
  --help            Show this help
`;

const expandHome = (value) => {
  if (!value) return value;
  if (value === '~') return os.homedir();
  if (value.startsWith('~/') || value.startsWith('~\\')) return path.join(os.homedir(), value.slice(2));
  return value;
};

const parseArgs = (argv) => {
  const parsed = {
    command: 'install',
    force: false,
    dir: process.env.KAREN_INSTALL_DIR || path.join(os.homedir(), '.local', 'bin'),
  };

  const args = [...argv];
  if (args[0] && !args[0].startsWith('-')) parsed.command = args.shift();

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--force') parsed.force = true;
    else if (arg === '--help' || arg === '-h') parsed.command = 'help';
    else if (arg === '--dir') {
      const value = args[index + 1];
      if (!value) throw new Error('--dir requires a path');
      parsed.dir = value;
      index += 1;
    } else if (arg.startsWith('--dir=')) {
      parsed.dir = arg.slice('--dir='.length);
    } else {
      throw new Error(`Unknown option: ${arg}`);
    }
  }

  parsed.dir = path.resolve(expandHome(parsed.dir));
  parsed.target = path.join(parsed.dir, commandName);
  return parsed;
};

const which = (command) => {
  const result = spawnSync(isWindows ? 'where' : 'which', [command], { encoding: 'utf8' });
  if (result.status !== 0) return null;
  return result.stdout.trim().split(/\r?\n/).find(Boolean) || null;
};

const runVersion = (command, args = ['--version']) => {
  const result = spawnSync(command, args, { encoding: 'utf8' });
  if (result.status !== 0) return null;
  return (result.stdout || result.stderr).trim().split(/\r?\n/)[0] || null;
};

const readPackageVersion = () => {
  try {
    return JSON.parse(fs.readFileSync(packageJson, 'utf8')).version || '0.0.0';
  } catch {
    return '0.0.0';
  }
};

const pathContains = (dir) => (process.env.PATH || '')
  .split(path.delimiter)
  .map((entry) => path.resolve(expandHome(entry || '.')))
  .includes(path.resolve(dir));

const marker = (target) => `Karen command generated by ${path.relative(path.dirname(target), source).replace(/\\/g, '/')}`;

const wrapperBody = (target) => {
  const relativeSource = path.relative(path.dirname(target), source).replace(/\\/g, '/');
  if (isWindows) {
    return `@echo off\r\nREM ${marker(target)}\r\nnode "%~dp0\\${relativeSource.replace(/\//g, '\\')}" %*\r\n`;
  }
  return `#!/usr/bin/env sh
# ${marker(target)}
exec node "$(dirname "$0")/${relativeSource}" "$@"
`;
};

const existingInstall = (target) => {
  if (!fs.existsSync(target)) return { exists: false, owned: false, kind: 'missing' };

  try {
    const stat = fs.lstatSync(target);
    if (stat.isSymbolicLink()) {
      const real = fs.realpathSync(target);
      return { exists: true, owned: real === source, kind: 'symlink', real };
    }
  } catch {
    return { exists: true, owned: false, kind: 'unknown' };
  }

  try {
    const body = fs.readFileSync(target, 'utf8');
    return {
      exists: true,
      owned: body.includes(source) || body.includes(marker(target)),
      kind: 'wrapper',
    };
  } catch {
    return { exists: true, owned: false, kind: 'unknown' };
  }
};

const printPathAdvice = (dir) => {
  if (pathContains(dir)) return;
  console.log('');
  console.log('PATH note: the install directory is not currently on PATH.');
  console.log(`Add this to your shell profile: export PATH="${dir}:$PATH"`);
};

const install = ({ target, dir, force }) => {
  if (!fs.existsSync(source)) {
    throw new Error(`Karen source not found: ${source}`);
  }

  const existing = existingInstall(target);
  if (existing.exists && !existing.owned && !force) {
    throw new Error(`Refusing to replace existing command: ${target}\nRun with --force if this is intentional.`);
  }

  fs.mkdirSync(dir, { recursive: true });
  fs.chmodSync(source, 0o755);
  if (existing.exists) fs.rmSync(target, { force: true });
  fs.writeFileSync(target, wrapperBody(target));
  if (!isWindows) fs.chmodSync(target, 0o755);

  console.log(`Karen installed: ${target}`);
  console.log(`Version: ${readPackageVersion()}`);
  console.log('Run: karen');
  printPathAdvice(dir);
};

const uninstall = ({ target }) => {
  const existing = existingInstall(target);
  if (!existing.exists) {
    console.log(`Karen is not installed at ${target}`);
    return;
  }
  if (!existing.owned) {
    throw new Error(`Refusing to remove command not owned by this repo: ${target}`);
  }
  fs.rmSync(target, { force: true });
  console.log(`Karen removed: ${target}`);
};

const status = ({ target, dir }) => {
  const existing = existingInstall(target);
  const pathHit = which('karen');
  console.log(`Karen source: ${source}`);
  console.log(`Install target: ${target}`);
  console.log(`Installed here: ${existing.exists ? 'yes' : 'no'}${existing.exists ? ` (${existing.kind})` : ''}`);
  console.log(`Owned by this repo: ${existing.owned ? 'yes' : 'no'}`);
  console.log(`On PATH: ${pathContains(dir) ? 'yes' : 'no'}`);
  console.log(`Resolved karen: ${pathHit || 'not found'}`);
  console.log(`Node: ${runVersion('node') || 'not found'}`);
  console.log(`OpenCode: ${runVersion(process.env.OPENCODE_BINARY || 'opencode') || 'not found'}`);
};

const doctor = (options) => {
  status(options);
  const problems = [];
  if (!fs.existsSync(source)) problems.push('Karen source file is missing.');
  if (!runVersion('node')) problems.push('Node.js is required to run the installed karen command.');
  if (!pathContains(options.dir)) problems.push('Install directory is not on PATH.');
  if (!runVersion(process.env.OPENCODE_BINARY || 'opencode')) problems.push('OpenCode CLI was not found. Karen can still open, but OpenCode proxy commands will fail.');

  if (problems.length === 0) {
    console.log('');
    console.log('Doctor: ready.');
    return;
  }

  console.log('');
  console.log('Doctor findings:');
  for (const problem of problems) console.log(`- ${problem}`);
};

const main = () => {
  const options = parseArgs(process.argv.slice(2));
  if (options.command === 'help') {
    console.log(usage.trim());
  } else if (options.command === 'install') {
    install(options);
  } else if (options.command === 'uninstall') {
    uninstall(options);
  } else if (options.command === 'status') {
    status(options);
  } else if (options.command === 'doctor') {
    doctor(options);
  } else {
    throw new Error(`Unknown command: ${options.command}\n\n${usage}`);
  }
};

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
